apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-server
  namespace: yolo
  labels:
    app: yolo-backend-server
spec:
  selector:
    matchLabels:
      app: yolo-backend-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-backend-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: yolo-backend-server
          image: nyachuba/yolo-backend:0.0.2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/

          ports:
            - containerPort: 5000
              name: yolo-backend-server
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: yolo
  labels:
    app: yolo-service
spec:
  selector:
    app: yolo-backend-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: LoadBalancer
