version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-network

  node-express:
    image: nyachuba/yolo-backend:0.0.2
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    volumes:
      - node-express:/app/node_modules
    networks:
      - yolo-network

  react:
    image: nyachuba/yolo-client:0.0.2
    ports:
      - "3000:80"
    depends_on:
      - node-express
    networks:
      - yolo-network

volumes:
  mongo-data:
  node-express:

networks:
  yolo-network:
    driver: bridge