apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: yolo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: yolo
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb

    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongodb
          image: mongo
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
              ephemeral-storage: "500Mi"

          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db

      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: yolo
  labels:
    app: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
