---
- name: Provisioning webservers
  hosts: all
  become: yes
  vars_files:
    - roles/vars/main.yml

  pre_tasks:
    - name: update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create yolo_net network
      docker_network:
        name: yolo_net
        driver: bridge

  roles:
    - database

    - backend

    - client
